# This workflow will install Python dependencies and will run the application for checking the server status

name: New World Server status

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  run:
    environment: master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        touch status.json
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Cache Server Status File
      uses: pat-s/always-upload-cache@v2.1.5
      env:
        cache-name: cache-server-status
      with:
        path: status.json
        key: ${{ runner.os }}-file-${{ hashFiles('status.json') }}
    - name: Check server status
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL}}
      run: |
        python server_status.py
