# This workflow will install Python dependencies and will run the application for checking the server status

name: New World Server status

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  run:
    environment: master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: server-status
    - name: Check server status
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL}}
      run: |
        python server_status.py
    - uses: actions/upload-artifact@v2
      with:
        name: server-status
        path: status.json